### ISSUE TITLE
Questions about this project.

### ISSUE THREAD

**Issue by Quick-Flash** [3x8/sulaco#1]
I'm working on the emuflight project. I'm not sure if you have heard of it, but I have an interest in the code that you are working on. I tried to do what you have done and put the kalman filter over the dterm. However, doing so has made it so that I can no longer connect my fc to the computer. No idea why that has happened. I'd love to chat with you some more about all of this stuff if you would be willing.

**Comment by adrianmiriuta** [comment]
@Quick-Flash
as I commented in your closed  #PR[205](https://github.com/emuflight/EmuFlight/pull/205#)

No , it only works for Kalman filter

you can scrap all gyro filtering (less delay)
simplify configuration (only one kalman filter after the PID)
As to practical flight ... I do not know !
I like the feel, it is locked and responsive, but I fly mostly ultralight tubular builds (LOS),
my other builds are also very light ...
It has to be tested in field for FPV ... so i cannot really tell.

My implementation is a quick hack of Butterflight,
where if kalman filter is chosen for dterm it applies to the PIDsum. (not to dTerm)

Although it only works with the kalman filter,
because the output of the PID has much higher noise with higher frequency,
PT1, BIQUAD and other frequency domain filters cannot handle it.
